var gulp = require('gulp')
var gutil = require('gutil')
var concat = require('gulp-concat')
var uglify = require('gulp-uglify')
var ngAnnotate = require('gulp-ng-annotate')
 
gulp.task('minifyAngular', function () {
  gulp.src(['public/angularApp.js', 'public/models/*.js', 'public/controllers/*.js'])
    .on('error', gutil.log)
    .pipe(concat('angularApp.min.js'))
    .on('error', gutil.log)
    .pipe(ngAnnotate())
    .on('error', gutil.log)
    .pipe(uglify())
    .on('error', gutil.log)
    //.pipe(sourcemaps.write())
    //.on('error', gutil.log)
    .pipe(gulp.dest('public/'))
})